name: Deploy client to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build client (if Node project)
        if: ${{ hashFiles('client/package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - if: ${{ hashFiles('client/package.json') != '' }}
        working-directory: client
        run: |
          npm ci --silent || npm i --silent
          npm run build --if-present

      - id: pick
        run: |
          for d in client/dist client/build client/out client; do
            if [ -d "$d" ]; then echo "publish_dir=$d" >> $GITHUB_OUTPUT; exit 0; fi
          done
          echo "publish_dir=client" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.pick.outputs.publish_dir }}

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
