name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  baseline:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Baseline CI check"

  node:
    if: ${{ hashFiles('**/package.json') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install / Build / Test (all package.json found)
        shell: bash
        run: |
          set -e
          mapfile -d '' pkgs < <(git ls-files -z '**/package.json')
          for f in "${pkgs[@]}"; do
            dir=$(dirname "$f")
            echo "=== Processing $dir ==="
            pushd "$dir" >/dev/null
            if [ -f package-lock.json ]; then
              npm ci --silent || npm i --silent
            else
              npm i --silent
            fi
            npm run build --if-present
            npm test --if-present
            popd >/dev/null
          done

      - name: Upload build artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            **/dist/**
            **/build/**
            **/out/**
          if-no-files-found: ignore
